package com.multithreading;

class MyThread3 extends Thread
{
	
}
public class Test2 //Getting & Setting Name of a Thread
{
	public static void main (String[]args)
	{
		System.out.println(Thread.currentThread().getName()); // Output: Main
		
		MyThread3 t = new MyThread3();
		System.out.println(t.getName());// Output: Thread-0 (Default name generated by JVM)
		
		Thread.currentThread().setName("Allu Arjun"); //Setting name of thread
		System.out.println(Thread.currentThread().getName());// Output: Allu Arjun (Customized name provided by programmer)
	}
}
/**
 * durga vid no. 80
*/
